// Mocks generated by Mockito 5.4.6 from annotations
// in pocket_union/test/services/category_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:pocket_union/domain/enum/category_host.dart' as _i8;
import 'package:pocket_union/domain/enum/sync_status.dart' as _i11;
import 'package:pocket_union/domain/models/category.dart' as _i7;
import 'package:pocket_union/domain/port/local/category_port_local.dart' as _i3;
import 'package:pocket_union/domain/port/utils/logger_port.dart' as _i12;
import 'package:pocket_union/dto/filter/category_filter_dto.dart' as _i9;
import 'package:pocket_union/dto/new_category_dto.dart' as _i5;
import 'package:pocket_union/dto/update_category_dto.dart' as _i10;
import 'package:supabase/supabase.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeFunctionsClient_0 extends _i1.SmartFake
    implements _i2.FunctionsClient {
  _FakeFunctionsClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSupabaseStorageClient_1 extends _i1.SmartFake
    implements _i2.SupabaseStorageClient {
  _FakeSupabaseStorageClient_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRealtimeClient_2 extends _i1.SmartFake
    implements _i2.RealtimeClient {
  _FakeRealtimeClient_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePostgrestClient_3 extends _i1.SmartFake
    implements _i2.PostgrestClient {
  _FakePostgrestClient_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoTrueClient_4 extends _i1.SmartFake implements _i2.GoTrueClient {
  _FakeGoTrueClient_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSupabaseQueryBuilder_5 extends _i1.SmartFake
    implements _i2.SupabaseQueryBuilder {
  _FakeSupabaseQueryBuilder_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSupabaseQuerySchema_6 extends _i1.SmartFake
    implements _i2.SupabaseQuerySchema {
  _FakeSupabaseQuerySchema_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePostgrestFilterBuilder_7<T1> extends _i1.SmartFake
    implements _i2.PostgrestFilterBuilder<T1> {
  _FakePostgrestFilterBuilder_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRealtimeChannel_8 extends _i1.SmartFake
    implements _i2.RealtimeChannel {
  _FakeRealtimeChannel_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CategoryLocalPort].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoryLocalPort extends _i1.Mock implements _i3.CategoryLocalPort {
  MockCategoryLocalPort() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<String> createCategory(_i5.NewCategoryDto? categoryDto) =>
      (super.noSuchMethod(
            Invocation.method(#createCategory, [categoryDto]),
            returnValue: _i4.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#createCategory, [categoryDto]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<_i7.Category?> getCategoryById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getCategoryById, [id]),
            returnValue: _i4.Future<_i7.Category?>.value(),
          )
          as _i4.Future<_i7.Category?>);

  @override
  _i4.Future<bool> deleteCategory(String? idCategory) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCategory, [idCategory]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<dynamic> deleteAllCategories() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAllCategories, []),
            returnValue: _i4.Future<dynamic>.value(),
          )
          as _i4.Future<dynamic>);

  @override
  _i4.Future<bool> createCategories(List<_i5.NewCategoryDto>? categories) =>
      (super.noSuchMethod(
            Invocation.method(#createCategories, [categories]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<List<_i7.Category>> createDefaultCategories(String? idCouple) =>
      (super.noSuchMethod(
            Invocation.method(#createDefaultCategories, [idCouple]),
            returnValue: _i4.Future<List<_i7.Category>>.value(<_i7.Category>[]),
          )
          as _i4.Future<List<_i7.Category>>);

  @override
  _i4.Future<List<_i7.Category>> getAllCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getAllCategories, []),
            returnValue: _i4.Future<List<_i7.Category>>.value(<_i7.Category>[]),
          )
          as _i4.Future<List<_i7.Category>>);

  @override
  _i4.Future<List<_i7.Category>> getAllCategoriesByCouple({String? coupleId}) =>
      (super.noSuchMethod(
            Invocation.method(#getAllCategoriesByCouple, [], {
              #coupleId: coupleId,
            }),
            returnValue: _i4.Future<List<_i7.Category>>.value(<_i7.Category>[]),
          )
          as _i4.Future<List<_i7.Category>>);

  @override
  _i4.Future<List<_i7.Category>> getCategoriesByHost(
    _i8.CategoryHost? host, {
    String? coupleId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getCategoriesByHost,
              [host],
              {#coupleId: coupleId},
            ),
            returnValue: _i4.Future<List<_i7.Category>>.value(<_i7.Category>[]),
          )
          as _i4.Future<List<_i7.Category>>);

  @override
  _i4.Future<List<_i7.Category>> getByFilter(_i9.CategoryFilterDto? filter) =>
      (super.noSuchMethod(
            Invocation.method(#getByFilter, [filter]),
            returnValue: _i4.Future<List<_i7.Category>>.value(<_i7.Category>[]),
          )
          as _i4.Future<List<_i7.Category>>);

  @override
  _i4.Future<bool> updateCategory(_i10.UpdateCategoryDto? dto) =>
      (super.noSuchMethod(
            Invocation.method(#updateCategory, [dto]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> updateCategories(List<_i10.UpdateCategoryDto>? dtos) =>
      (super.noSuchMethod(
            Invocation.method(#updateCategories, [dtos]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<List<_i7.Category>> getCategoriesNeedingSync() =>
      (super.noSuchMethod(
            Invocation.method(#getCategoriesNeedingSync, []),
            returnValue: _i4.Future<List<_i7.Category>>.value(<_i7.Category>[]),
          )
          as _i4.Future<List<_i7.Category>>);

  @override
  _i4.Future<void> updateSyncStatus(
    String? categoryId,
    _i11.SyncStatus? status, {
    DateTime? lastSyncAt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateSyncStatus,
              [categoryId, status],
              {#lastSyncAt: lastSyncAt},
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [SupabaseClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupabaseClient extends _i1.Mock implements _i2.SupabaseClient {
  MockSupabaseClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FunctionsClient get functions =>
      (super.noSuchMethod(
            Invocation.getter(#functions),
            returnValue: _FakeFunctionsClient_0(
              this,
              Invocation.getter(#functions),
            ),
          )
          as _i2.FunctionsClient);

  @override
  _i2.SupabaseStorageClient get storage =>
      (super.noSuchMethod(
            Invocation.getter(#storage),
            returnValue: _FakeSupabaseStorageClient_1(
              this,
              Invocation.getter(#storage),
            ),
          )
          as _i2.SupabaseStorageClient);

  @override
  _i2.RealtimeClient get realtime =>
      (super.noSuchMethod(
            Invocation.getter(#realtime),
            returnValue: _FakeRealtimeClient_2(
              this,
              Invocation.getter(#realtime),
            ),
          )
          as _i2.RealtimeClient);

  @override
  _i2.PostgrestClient get rest =>
      (super.noSuchMethod(
            Invocation.getter(#rest),
            returnValue: _FakePostgrestClient_3(this, Invocation.getter(#rest)),
          )
          as _i2.PostgrestClient);

  @override
  Map<String, String> get headers =>
      (super.noSuchMethod(
            Invocation.getter(#headers),
            returnValue: <String, String>{},
          )
          as Map<String, String>);

  @override
  _i2.GoTrueClient get auth =>
      (super.noSuchMethod(
            Invocation.getter(#auth),
            returnValue: _FakeGoTrueClient_4(this, Invocation.getter(#auth)),
          )
          as _i2.GoTrueClient);

  @override
  set functions(_i2.FunctionsClient? value) => super.noSuchMethod(
    Invocation.setter(#functions, value),
    returnValueForMissingStub: null,
  );

  @override
  set storage(_i2.SupabaseStorageClient? value) => super.noSuchMethod(
    Invocation.setter(#storage, value),
    returnValueForMissingStub: null,
  );

  @override
  set realtime(_i2.RealtimeClient? value) => super.noSuchMethod(
    Invocation.setter(#realtime, value),
    returnValueForMissingStub: null,
  );

  @override
  set rest(_i2.PostgrestClient? value) => super.noSuchMethod(
    Invocation.setter(#rest, value),
    returnValueForMissingStub: null,
  );

  @override
  set headers(Map<String, String>? headers) => super.noSuchMethod(
    Invocation.setter(#headers, headers),
    returnValueForMissingStub: null,
  );

  @override
  _i2.SupabaseQueryBuilder from(String? table) =>
      (super.noSuchMethod(
            Invocation.method(#from, [table]),
            returnValue: _FakeSupabaseQueryBuilder_5(
              this,
              Invocation.method(#from, [table]),
            ),
          )
          as _i2.SupabaseQueryBuilder);

  @override
  _i2.SupabaseQuerySchema schema(String? schema) =>
      (super.noSuchMethod(
            Invocation.method(#schema, [schema]),
            returnValue: _FakeSupabaseQuerySchema_6(
              this,
              Invocation.method(#schema, [schema]),
            ),
          )
          as _i2.SupabaseQuerySchema);

  @override
  _i2.PostgrestFilterBuilder<T> rpc<T>(
    String? fn, {
    Map<String, dynamic>? params,
    dynamic get = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#rpc, [fn], {#params: params, #get: get}),
            returnValue: _FakePostgrestFilterBuilder_7<T>(
              this,
              Invocation.method(#rpc, [fn], {#params: params, #get: get}),
            ),
          )
          as _i2.PostgrestFilterBuilder<T>);

  @override
  _i2.RealtimeChannel channel(
    String? name, {
    _i2.RealtimeChannelConfig? opts = const _i2.RealtimeChannelConfig(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#channel, [name], {#opts: opts}),
            returnValue: _FakeRealtimeChannel_8(
              this,
              Invocation.method(#channel, [name], {#opts: opts}),
            ),
          )
          as _i2.RealtimeChannel);

  @override
  List<_i2.RealtimeChannel> getChannels() =>
      (super.noSuchMethod(
            Invocation.method(#getChannels, []),
            returnValue: <_i2.RealtimeChannel>[],
          )
          as List<_i2.RealtimeChannel>);

  @override
  _i4.Future<String> removeChannel(_i2.RealtimeChannel? channel) =>
      (super.noSuchMethod(
            Invocation.method(#removeChannel, [channel]),
            returnValue: _i4.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#removeChannel, [channel]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<List<String>> removeAllChannels() =>
      (super.noSuchMethod(
            Invocation.method(#removeAllChannels, []),
            returnValue: _i4.Future<List<String>>.value(<String>[]),
          )
          as _i4.Future<List<String>>);

  @override
  _i4.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [LoggerPort].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoggerPort extends _i1.Mock implements _i12.LoggerPort {
  MockLoggerPort() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void info(String? message) => super.noSuchMethod(
    Invocation.method(#info, [message]),
    returnValueForMissingStub: null,
  );

  @override
  void debug(String? message) => super.noSuchMethod(
    Invocation.method(#debug, [message]),
    returnValueForMissingStub: null,
  );

  @override
  void warning(String? message) => super.noSuchMethod(
    Invocation.method(#warning, [message]),
    returnValueForMissingStub: null,
  );

  @override
  void error(String? message, {Object? error, StackTrace? stackTrace}) =>
      super.noSuchMethod(
        Invocation.method(
          #error,
          [message],
          {#error: error, #stackTrace: stackTrace},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void logObject(Object? object, {String? label}) => super.noSuchMethod(
    Invocation.method(#logObject, [object], {#label: label}),
    returnValueForMissingStub: null,
  );
}
